---
title: Untitled
author: First Last
date: last-modified
date-format: long
anonymized: false # Change this to true if you need to blind it for review
abstract: "Here's where you'd put your abstract" # optional
wordcount: "{{wordcountref}}" # or you can calculate it manually, or eliminate
# bibliography: 
spaced-notes: false # Should footnotes be double-spaced?
format:
    manuscript-pdf: default
---

# Introduction

This [Quarto](https://quarto.org/) [template](https://quarto.org/docs/extensions/formats.html) generates a PDF that is:

- Double spaced
- With 12 point text (including in footnotes!)
- With one-inch margins
- Using Times New Roman as the main font
- Using Helvetica for section headings
- Optionally anonymized
- Optionally has double-spaced footnotes (as required by, e.g. [The Journal of Politics](https://www.journals.uchicago.edu/toc/jop/current))

These choices are compatible with the submission requirements of a large number of (at least political science) journals.

# PDF Engine

Note that this format uses the pdflatex PDF engine rather than xelatex.

# Word Count

Note that there is an included automatic word count tool, but for now it seems to be a bit of an overestimate.
An alternative is to replace `"{{wordcountref}}"` with your own word count.
One relatively easy and seemingly accurate tool to count the words in a Quarto document is the [wordcount add-in for RStudio](https://github.com/benmarwick/wordcountaddin).

# References

No particular reference style is suggested or enforced by this template, that's up to you to select based either on personal preference or journal requirements.
